project_id = "lmkxpzemfvmffxppxzky"

[functions.mpesa-stk-push]
verify_jwt = false

[functions.mpesa-callback]
verify_jwt = false

[functions.mpesa-stk-query]
verify_jwt = false

[functions.send-booking-confirmation]
verify_jwt = false

[functions.send-payment-initiation]
verify_jwt = false

[functions.send-host-booking-notification]
verify_jwt = false

[functions.approve-items]
verify_jwt = true

[functions.hash-pin]
verify_jwt = false

[functions.verify-item-access]
verify_jwt = false

[functions.paystack-initialize]
verify_jwt = false

[functions.paystack-verify]
verify_jwt = false
